jQuery ->
  $.ajax
    url: 'https://apis.google.com/js/client:plus.js?onload=gpAsyncInit'
    dataType: 'script'
    cache: true

window.gpAsyncInit = ->
  $('.googleplus-login').removeAttr('disabled').click (e) ->
    e.preventDefault()
    gapi.auth.authorize {
      immediate: true
      response_type: 'code'
      cookie_policy: 'single_host_origin'
      client_id: '1094586320801-nvg6i4lnlikepj2tl5unqomc1qtm6m5i.apps.googleusercontent.com'
      scope: 'email profile'
    }, (response) ->
      if response and !response.error
        response['user[username]'] = $('#user_username').val()
        response['g-recaptcha-response'] = $('#g-recaptcha-response').val()
        response['authenticity_token'] = $('input[name="authenticity_token"]').val()
        response['utf8'] = $('input[name="utf8"]').val()
        jQuery.ajax
          type: 'POST'
          url: '/auth/google_oauth2/callback'
          dataType: 'json'
          data: response
          success: (json) ->
            location.href = '/'
            return
      else
        # google authentication failed
      return
    return
  return

# ---
# generated by js2coffee 2.0.1

