# Place all the behaviors and hooks related to the matching controller here.
# All this logic will automatically be available in application.js.
# You can use CoffeeScript in this file: http://jashkenas.github.com/coffee-script/
$(document).ready ->
  $("#user_username").autocomplete
    source: (request, response) ->
      params =
        exac: true
        term: request.term

      $.get "/users/complete", params, (data) ->
        if data.length > 0
          $("#user_username").css('background-color','#fdd')
          alert "Someone already has that username. Try another?" # <%= I18n.t(:username_taken)%>
        else
          $("#user_username").css('background-color','#dfd')
    delay: 1000
  $.ajax
    url: 'https://apis.google.com/js/client:plus.js?onload=googleInit'
    dataType: 'script'
    cache: true
# TODO aggiungere altri provider
@googleInit = ->
  $('.googleplus-login').removeAttr('disabled').click (e) ->
    e.preventDefault()
    gapi.auth.authorize {
      immediate: true
      response_type: 'code'
      cookie_policy: 'single_host_origin'
      client_id: '1094586320801-nvg6i4lnlikepj2tl5unqomc1qtm6m5i.apps.googleusercontent.com'
      scope: 'email profile'
    }, (response) ->
      if response and !response.error
        response['user[username]'] = $('#user_username').val()
        response['g-recaptcha-response'] = $('#g-recaptcha-response').val()
        response['authenticity_token'] = $('input[name="authenticity_token"]').val()
        response['utf8'] = $('input[name="utf8"]').val()
        jQuery.ajax
          type: 'POST'
          url: '/auth/google_oauth2/callback'
          dataType: 'json'
          data: response
          success: (json) ->
            location.href = '/'
            return
      else
        # google authentication failed
      return
    return
  return

# ---
# generated by js2coffee 2.0.1

